name = "php-library"
title = "PHP Library Manual"

eol = true

intersphinx = ["https://www.mongodb.com/docs/manual/objects.inv"]

toc_landing_pages = [
    "/reference/class/MongoDBClient",
    "/reference/class/MongoDBCollection",
    "/reference/class/MongoDBDatabase",
    "/reference/class/MongoDBGridFSBucket",
    "/reference/result-classes",
    "/reference/write-result-classes"
]

[substitutions]
php-library = "MongoDB PHP Library"

[constants]
php-library = "PHP Library"
current-url-base = "https://www.mongodb.com/docs/php-library/current"

[[banners]]
targets = ["*"]
variant = "info"
value = """\
    This version of the documentation is archived and no longer supported. View the `current documentation <{+current-url-base+}/>`__ to learn how to `upgrade your version of the {+php-library+} <{+current-url-base+}/upgrade/#how-to-upgrade>`__.\
    """
